"""Initial migration

Revision ID: 5950638db3bd
Revises: 
Create Date: 2026-05-02 22:50:28.564903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5950638db3bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accumulated_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('products_remaining', sa.Float(), nullable=True),
    sa.Column('auto_remaining', sa.Float(), nullable=True),
    sa.Column('other_remaining', sa.Float(), nullable=True),
    sa.Column('daily_limit_products', sa.Float(), nullable=True),
    sa.Column('daily_limit_auto', sa.Float(), nullable=True),
    sa.Column('daily_limit_other', sa.Float(), nullable=True),
    sa.Column('end_of_day_balance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_index('ix_accumulated_daily_date', 'accumulated_daily', ['date'], unique=False)
    op.create_index(op.f('ix_accumulated_daily_id'), 'accumulated_daily', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', 'ACCUMULATIVE', name='categorytype'), nullable=False),
    sa.Column('is_accumulative', sa.Boolean(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('credit_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('accrued_interest', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_cards_id'), 'credit_cards', ['id'], unique=False)
    op.create_table('credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('planned_amount', sa.Float(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('actual_amount', sa.Float(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credits_id'), 'credits', ['id'], unique=False)
    op.create_table('salary_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('advance_date', sa.Date(), nullable=True),
    sa.Column('advance_amount', sa.Float(), nullable=True),
    sa.Column('salary_date', sa.Date(), nullable=True),
    sa.Column('salary_amount', sa.Float(), nullable=True),
    sa.Column('advance_received', sa.Boolean(), nullable=True),
    sa.Column('salary_received', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_schedule_id'), 'salary_schedule', ['id'], unique=False)
    op.create_index('ix_salary_schedule_year_month', 'salary_schedule', ['year_month'], unique=True)
    op.create_table('monthly_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('planned_amount', sa.Float(), nullable=True),
    sa.Column('actual_amount', sa.Float(), nullable=True),
    sa.Column('payment_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_budgets_id'), 'monthly_budgets', ['id'], unique=False)
    op.create_index('ix_monthly_budgets_year_month', 'monthly_budgets', ['year_month'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.Enum('PLAN', 'ACTUAL', name='transactiontype'), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_date_type', 'transactions', ['date', 'transaction_type'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index('ix_transactions_date_type', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_monthly_budgets_year_month', table_name='monthly_budgets')
    op.drop_index(op.f('ix_monthly_budgets_id'), table_name='monthly_budgets')
    op.drop_table('monthly_budgets')
    op.drop_index('ix_salary_schedule_year_month', table_name='salary_schedule')
    op.drop_index(op.f('ix_salary_schedule_id'), table_name='salary_schedule')
    op.drop_table('salary_schedule')
    op.drop_index(op.f('ix_credits_id'), table_name='credits')
    op.drop_table('credits')
    op.drop_index(op.f('ix_credit_cards_id'), table_name='credit_cards')
    op.drop_table('credit_cards')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_accumulated_daily_id'), table_name='accumulated_daily')
    op.drop_index('ix_accumulated_daily_date', table_name='accumulated_daily')
    op.drop_table('accumulated_daily')
    # ### end Alembic commands ###
